# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
-
  id: "ss5"
  main: ./cmd/server/main.go
  binary: "ss5"
  goos:
    - linux
    - windows
    - android
  goarch:
    - amd64
    - arm64
  ignore:
    - goos: windows
      goarch: arm64
    - goos: android
      goarch: amd64
  env:
    - CGO_ENABLED=0
archives:
-
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
    arm64: arm64
  files:
    - ss5.json
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
